[workspace]
members = [
    "crates/terminal-app",
    "crates/terminal-core",
    "crates/terminal-pty",
    "crates/terminal-renderer",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
anyhow = "1.0"
arboard = { version = "3.6", default-features = false }
bytemuck = { version = "1.21", features = ["derive"] }
crossbeam-channel = "0.5"
glyphon = "0.12"
log = "0.4"
open = "5.3"
pollster = "0.4"
portable-pty = "0.9"
serde = { version = "1.0", features = ["derive"] }
smol_str = "0.2"
thiserror = "2.0"
toml = "0.9"
unicode-segmentation = "1.12"
unicode-width = "0.2"
vte = "0.15"
wgpu = "30.0"
winit = "0.30"
muda = "0.17"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
